# Generated by Django 5.1.4 on 2025-01-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_detail_u_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='u_status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=10),
        ),
    ]
