# Generated by Django 5.1.4 on 2025-01-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_detail_u_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=30)),
                ('b_desc', models.TextField()),
                ('b_logo', models.ImageField(upload_to='logo')),
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='user_typename',
            field=models.CharField(choices=[('User', '1'), ('Buyer', '2'), ('Seller', '3'), ('Rent', '4')], max_length=30),
        ),
        migrations.CreateModel(
            name='new_furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fu_model_name', models.CharField(max_length=30)),
                ('fu_desc', models.TextField()),
                ('fu_price', models.IntegerField()),
                ('fu_image', models.ImageField(upload_to='new furniture')),
                ('available_qty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=20)),
                ('fu_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.furniture_category')),
                ('n_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand')),
            ],
        ),
        migrations.CreateModel(
            name='new_furniture_buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_dt', models.DateTimeField(auto_now_add=True)),
                ('fu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.new_furniture')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='old_furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=30)),
                ('o_desc', models.TextField()),
                ('o_price', models.IntegerField()),
                ('o_image', models.ImageField(upload_to='old furniture')),
                ('o_available_qty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=20)),
                ('o_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand')),
                ('o_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.furniture_category')),
            ],
        ),
        migrations.CreateModel(
            name='old_furniture_buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_booking_dt', models.DateTimeField(auto_now_add=True)),
                ('o_fu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.old_furniture')),
                ('user_booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='rent_furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_f_name', models.CharField(max_length=30)),
                ('r_desc', models.TextField()),
                ('r_price', models.IntegerField()),
                ('r_image', models.ImageField(upload_to='rent furniture')),
                ('r_available_qty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=20)),
                ('r_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand')),
                ('r_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.furniture_category')),
            ],
        ),
        migrations.CreateModel(
            name='rentfurniture_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_startdate', models.DateField()),
                ('r_enddate', models.DateField()),
                ('rent_bookdatetime', models.DateTimeField(auto_now_add=True)),
                ('rent_f_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rent_furniture')),
                ('rent_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
    ]
