# Generated by Django 5.1.4 on 2025-01-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_brand_alter_role_user_typename_new_furniture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='user_typename',
            field=models.CharField(choices=[('1', 'User'), ('2', 'Buyer'), ('3', 'Seller'), ('4', 'Rent')], max_length=30),
        ),
    ]
